name: Build Tarball

on:
  push:
    branches:
      - branchAutomake

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Install Dependencies
        run: sudo apt update && sudo apt install -y automake autoconf libtool
      - name: Build Tarball
        run: |
          aclocal
          autoconf
          automake --add-missing
          ./configure
          make dist
