name: Build and Test

on:
  push:
    branches:
      - branchAutoTest

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Install Dependencies
        run: sudo apt update && sudo apt install -y g++
      - name: Build and Test
        run: |
          make
          make check
