name: Build Debian Package

on:
  push:
    branches:
      - branchAutoPackage

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Install Dependencies
        run: sudo apt update && sudo apt install -y dh-make dpkg-dev g++
      - name: Build Debian Package
        run: |
          dpkg-buildpackage -us -uc
